type: hyperskill
title: Gitman
language: English
summary: "<p>Create a program that automates common Git tasks for software developers.\
  \ Initialize the repository, create and rebase a branch, modify a commit, make a\
  \ hotfix, and share your project with your future colleagues on GitHub.</p><br/><br/>Learn\
  \ more at <a href=\"https://hyperskill.org/projects/296?utm_source=ide&utm_medium=ide&utm_campaign=ide&utm_content=project-card\"\
  >https://hyperskill.org/projects/296</a>"
programming_language: Python
environment: unittest
content:
  - Gitman
mode: Study
